### ISSUE TITLE
Crashes when no MRC files present

### ISSUE THREAD

**Issue by janden** [PrincetonUniversity/APPLEpicker-python#10]
If you give a directory that doesn't contain any MRC files, `apple.py` crashes with

```
converting 0 mrc files..
Traceback (most recent call last):
  File "apple.py", line 281, in <module>
    apple.pick_particles()
  File "apple.py", line 171, in pick_particles
    Apple.process_micrograph(data, filenames[0])
IndexError: list index out of range
```
It would be better if it just terminate instead (perhaps after warning that no MRC files were found).

**Comment by rbrook** [comment]
Added warning and termination for empty mrc dir and wrong mrc dir.
