### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: \micrograph_applepick.star

### ISSUE THREAD

**Issue by SanatMoharir** [PrincetonUniversity/APPLEpicker-python#17]
Firstly, whenever I run the code it identifies my MRC file and it does some processing for some 14-15 minutes and it creates the 'star_dir' folder and after this nearly 15 minutes time, it's giving me the following error. And that folder 'star_dir' stays empty. No  '.star'  file is created. Can anyone please help me?  Thanks in advance !!!

converting 1 mrc files..
Processing micrograph.mrc..
Traceback (most recent call last):
  File "run.py", line 49, in <module>
    apple.pick_particles()
  File "C:\Users\Sanat Mohrir\Documents\GitHub\APPLEpicker-python\apple\apple.py", line 170, in pick_particles
    Apple.process_micrograph(data, filenames[0])
  File "C:\Users\Sanat Mohrir\Documents\GitHub\APPLEpicker-python\apple\apple.py", line 245, in process_micrograph
    centers = picker.extract_particles(segmentation)
  File "C:\Users\Sanat Mohrir\Documents\GitHub\APPLEpicker-python\apple\picking.py", line 285, in extract_particles
    with open(applepick_path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Sanat Mohrir\\Documents\\GitHub\\APPLEpicker-python\\star_dir\\mrc\\micrograph_applepick.star'

**Comment by ayeltg** [comment]
Can you try manually specifying the output directory as some existing directory? 
For example, if you would like the existing star_dir to be the output directory, just add
 -o star_dir
to the command. This will bypass the code that automatically sets your output directory.

**Comment by SanatMoharir** [comment]
@ayeltg  I have already done that but still same error is showing. Specified file is getting created but it is empty. Please can you tell me another way?

**Comment by ayeltg** [comment]
From the error message, this looks to me to be a problem with parsing the file name. In line 277 of picking.py, can you change the command
"name_list = self.filenames.split("/")"
to
"name_list = self.filenames.split("\")" ? And please let me know if this works.

**Comment by ayeltg** [comment]
Correction: the new command should be "name_list = self.filenames.split("\")"

**Comment by ayeltg** [comment]
`name_list = self.filenames.split("\")`

**Comment by ayeltg** [comment]
The number of query images is set to 
`x = (4000^2) / (q ** 2) *9`
where q is the particle size. 
The tau_2 parameter is (by default) 30% of x. I suggest you use the config.py file and set tau_2 to be higher, about 45%-55% of x. 
Also, the apple picker sometimes works better on micrographs that contains the sum of all frames without motion correction.

**Comment by janden** [comment]
I'm not sure it's supposed to be
```
name_list = self.filenames.split(".")
```
For filenames, we should be using `os.path.split` and `os.path.basename` to make sure things are handled properly on different platforms.

**Comment by janden** [comment]
Fixed by 90b31781792f4e1da4b9d86e3d66d92897bd17e1. Closing.
