### ISSUE TITLE
AttributeError: module 'dask.array.numpy_compat' has no attribute 'take_along_axis'

### ISSUE THREAD

**Issue by heejongkim** [PrincetonUniversity/APPLEpicker-python#26]
Hi

After following the instruction to install the package, I executed the first command (python run.py -h) and I got the following error msg.

    take_along_axis = npcompat.take_along_axis
AttributeError: module 'dask.array.numpy_compat' has no attribute 'take_along_axis'

It seems like the version incompatibility issue but I get different issues down the road if match the numpy, scipy, and scikit-learn accordingly.

Would it be possible if you can take a look at the issue and possibly provide your working environment's full package versions so that I can create an appropriate virtual environment for this software?

Thank you.

best,
heejong

**Comment by janden** [comment]
It sounds like you've got some other package installed that's interfering with the standard NumPy (the line you're mentioning does not exist in the Apple picker code). Try installing in a fresh virtual environment and running the code.

Also, this code is not really being maintained at this point. You may have better success using the Apple picker module of ASPIRE: https://github.com/ComputationalCryoEM/ASPIRE-Python/.

**Comment by heejongkim** [comment]
Hi @janden 
Thanks for getting back to this thread.
I think it's not coming from the apple picker but from the package that apple picker depends on.
In order to get this error, I made a fresh virtual environment and fixed sub-dependency version incompatibility first. 
Hope this thread is helpful for other people who may want to give it a shot.

Thanks for the info for the ASPIRE-python and I will give it a shot.

best,
heejong
